### PR TITLE
Add GoT theme with RGB loop example

### PR DESCRIPTION
**Pull request by pllim**
Thanks for the sprint session. I had a lot of fun! In case you are a Game of Thrones fan, you might enjoy this one.

Credit for the song notes go to https://www.instructables.com/id/Game-Of-Thrones-Theme-on-Arduino/

p.s. You don't have to merge this, I am mainly opening this PR to share and so I don't lose the code.

p.p.s. Game of Thrones is not for kids!

### CODE REVIEW

**Comment by pllim** [comment]
@jdavies-st , if you managed to improve this, feel free to PR against my PR.

**Review by kattni — CHANGES_REQUESTED** [review]
This is great! Can you move it to the `Attendee_Examples` folder? I'd love to add it to the repo!

**Comment by pllim** [comment]
Thanks for the review, @kattni . I have moved the file as requested.

p.p.p.s. The time multiplicative factor (`fac`) needs to be adjusted for a different chip model. I found that this default value worked well with the swag bag chip, but had to be increased to 0.5 for the chip in the blue tin box that Microsoft handed out.

**Comment by kattni** [comment]
@pllim There shouldn't have been any difference between the two. The only difference was the color of the board. There are sometimes small differences in manufacturing that could have caused this issue.

**Review by kattni — APPROVED** [review]
Thanks for submitting this!

**Pull request merged**
