### PR TITLE
Replace Python colours with a pulsating Python logo (ish). :-)

### PR DESCRIPTION
**Pull request by ntoll**
This PR introduces thee changes:

1. The Python colours are closer to the colours used in the logo (more pastel-y, IYSWIM).
2. The arrangement of the LEDs is such that it suggests the Python logo.
3. The whole thing gently pulsates for a duration that's timed to suggest breathing.

Please don't merge if you don't want to..! I was having fun playing around with your code and thought the Python colours branch of the conditional could be jazzed up a bit. :smiley: If you do accept the PR, please don't hesitate to rewrite my contribution... I'm painfully aware that my current knowledge of CPX APIs is way out of date and that there's likely a better way to do this.

Awesome work BTW... folks are going to love this. :+1:  :microscope: :snake: :heart:

### CODE REVIEW

**Review by kattni — COMMENTED** [review]
@ntoll This is great! I love it! The thing is, my goal is to keep this example as simple as possible while demonstrating enough of the features to get people started. I would like to change the Python colors to your colors in the demo, but I'd rather not add the pulsating logo bit to it. 

However! If it's alright with you, I'd like to include it as a separate example in this repo which we are linking many places to participants for the Open Spaces and beyond. Let me know if that works for you!

**Comment by ntoll** [comment]
@kattni no need to ask if it's OK with me... I'm just happy you folks are making all this happen at PyCon and engaging with the community. Happy I could help, and please do keep it up! :-)

**Comment by kattni** [comment]
@ntoll Here it is! Thanks again! https://github.com/adafruit/PyCon2019/blob/master/Circuit_Playground_Express_cpx_Library_Examples/cpx_pulsing_python_logo.py

**Comment by ntoll** [comment]
@kattni awesomeness on stilts..! :-)

**Pull request closed without merging**
